/* This file was generated by syncqt. */
#ifndef QT_ACTIVEQT_VERSION_H
#define QT_ACTIVEQT_VERSION_H

#define ACTIVEQT_VERSION_STR "5.15.14"

#define ACTIVEQT_VERSION 0x050F0E

#endif // QT_ACTIVEQT_VERSION_H
