/* This file was generated by syncqt. */
#ifndef QT_QTQUICK_VERSION_H
#define QT_QTQUICK_VERSION_H

#define QTQUICK_VERSION_STR "5.15.14"

#define QTQUICK_VERSION 0x050F0E

#endif // QT_QTQUICK_VERSION_H
